pipeline {
    agent any

    options { 
  		// avoid concurrent builds
  		disableConcurrentBuilds()
	}

    environment {
    	CREDENTIALS_ID ='vfpt-edis'
        BUCKET = 'rawingest'
        PATTERN_CONTROL_SHEET = 'ngbi/control_sheet/pprd/*.yml'
        PATTERN_DAG_CONFIG = 'ngbi/dag_config/*.yml'
        LOCAL_DIR = '/var/jenkins_tmp/'
    }

    stages {
        stage('Download from GCS') {
            steps {
            	// Download from GCS bucket object named PATTERN to directory LOCAL_DIR.
                step([$class: 'DownloadStep', 
                	credentialsId: env.CREDENTIALS_ID,
                	bucketUri: "gs://${env.BUCKET}/${env.PATTERN_CONTROL_SHEET}",
                	localDirectory: env.LOCAL_DIR])

                step([$class: 'DownloadStep', 
                	credentialsId: env.CREDENTIALS_ID,
                	bucketUri: "gs://${env.BUCKET}/${env.PATTERN_DAG_CONFIG}",
                	localDirectory: env.LOCAL_DIR])
            }
        }

        stage('List downloaded files') {
        	steps {
        		sh "ls $LOCAL_DIR"
        	}
        }
    }
}

